### ISSUE TITLE
define ExternalLink CustomResource

### ISSUE THREAD

**Issue by ShotaKitazawa** [ShotaKitazawa/kube-portal#386]
```yaml
apiVersion: kubeportal.kanatakita.com/v1alpha1
kind: ExternalLink
spec:
  name: string
  iconUrl: string
  href: http://example.com/hoge/fuga
  tags: [string]
```
